### ISSUE TITLE
Cheater

### ISSUE THREAD

**Issue by Ladla420** [U7P4L-IN/User_Agents#1]
Bye

**Comment by Ladla420** [comment]
HE STOLLED MY SCRIPT  AND UPLOAD THIS SCRIPT PLEASE REMOVE AS SOON AS POSSIBLE

**Comment by Ladla420** [comment]
COPY PASTER THIS SCRIPT IS MINE AND YOU USE THIS BY ENCRYPTING IT 🙄😅

**Comment by PrinceHamzaYT** [comment]
He were useing another person script without permission

**Comment by dcofficial** [comment]
MDRCHOD 🥵🚬

**Comment by U7P4L-IN** [comment]
Teri ma ki x*d

**Comment by U7P4L-IN** [comment]
B
